import { AttackCrest } from '@/Game/Die/Crest/AttackCrest';
import { DefenseCrest } from '@/Game/Die/Crest/DefenseCrest';
import { MagicCrest } from '@/Game/Die/Crest/MagicCrest';
import { MovementCrest } from '@/Game/Die/Crest/MovementCrest';
import { SummonCrest } from '@/Game/Die/Crest/SummonCrest';
import { TrapCrest } from '@/Game/Die/Crest/TrapCrest';
import { Color } from '@/Utils/Color';

const dungeon = {
  '0': 'OOOOOOPOOOOOO',
  '1': 'OOOOOOOOOOOOO',
  '2': 'OOOOOOOOOOOOO',
  '3': 'OOOOOOOOOOOOO',
  '4': 'OOOOOOOOOOOOO',
  '5': 'OOOOOOOOOOOOO',
  '6': 'OOOOOOOOOOOOO',
  '7': 'OOOOOOOOOOOOO',
  '8': 'OOOOOOOOOOOOO',
  '9': 'OOOOOOOOOOOOO',
  '10': 'OOOOOOOOOOOOO',
  '11': 'OOOOOOOOOOOOO',
  '12': 'OOOOOOOOOOOOO',
  '13': 'OOOOOOOOOOOOO',
  '14': 'OOOOOOOOOOOOO',
  '15': 'OOOOOOOOOOOOO',
  '16': 'OOOOOOOOOOOOO',
  '17': 'OOOOOOOOOOOOO',
  '18': 'OOOOOOpOOOOOO',
};

export const Settings = Object.freeze({
  board: {
    dungeon,
    size: {
      x: dungeon[0].length,
      y: Object.keys(dungeon).length,
    },
    tile: {
      size: 45,
      offset: 1,
    },
    color: {
      regular: new Color(86, 36, 36, 0.5),
      active: new Color(176, 190, 197),
      inRange: new Color(176, 190, 197),
      onPath: new Color(51, 255, 153),
    },
  },
  debug: true,
  dice: {
    crests: {
      A: AttackCrest,
      D: DefenseCrest,
      G: MagicCrest,
      M: MovementCrest,
      S: SummonCrest,
      T: TrapCrest,
    },
  },
  monsters: {
    radius: 5,
    types: ['dragon', 'zombie', 'beast', 'warrior', 'spellcaster'],
    data: {
      '1': {
        name: 'Akihiron',
        type: 'beast',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 30,
        ability:
          'This monster can attack an opposing monster that is 2 squares away. When it uses this Special Ability, place 1 Damage Marker on Akihiron. [Gx1]',
        crests: 'SSMMAT2',
      },
      '2': {
        name: 'Alligator\'s Sword',
        type: 'beast',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability:
          'During a battle, this monster can add an additional 20 Attack Power points to itself if it attacks a monster from the Warrior type',
        crests: 'SSSSMD2',
      },
      '3': {
        name: 'Alpha The Magnet Warrior',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'While one Gamma The Magnet Warrior is in the dungeon, this monster adds 10 extra Defense Power points to itself',
        crests: 'SSSM2A2G',
      },
      '4': {
        name: 'Aqua Madoor',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 20,
        lifepoint: 10,
        ability: '',
        crests: 'SSSSMD2',
      },
      '5': {
        name: 'Archfiend of Gilfer',
        type: 'spellcaster',
        level: 3,
        attack: 30,
        defense: 30,
        lifepoint: 10,
        ability:
          'You can only activate this ability when this monster inflicts damage to an opponent\'s monster. That monster cannot move during your opponent\'s next turn. [Gx1] \nFor one turn, one monster in the dungeon will lose its Flying ability. [Tx2]',
        crests: 'SSMMAT2',
      },
      '6': {
        name: 'Armed Ninja',
        type: 'warrior',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'This monster gains the Flying ability for one turn. [Gx1]',
        crests: 'SSSSMD2',
      },
      '7': {
        name: 'Armored Zombie',
        type: 'zombie',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability:
          'When this power is activated, no other monster(s), including Armored Zombie, can move. When the turn ends, Armored Zombie is destroyed. [Tx2]',
        crests: 'SSSM2A2G',
      },
      '8': {
        name: 'Assassin',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'This monster can stop one opposing monster\'s Special Ability when the opposing monster uses it. This effect only works against the targeted monster; you will have to spend 3 more Trap Crests to affect an additional monster. [Tx3]',
        crests: 'SSSM2A2G',
      },
      '9': {
        name: 'B. eye Ultimate Dragon',
        type: 'dragon',
        level: 4,
        attack: 50,
        defense: 40,
        lifepoint: 60,
        ability: 'Movement limited to 1 square per turn.',
        crests: 'SM2ADG2T',
      },
      '10': {
        name: 'B. eye White Dragon',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 30,
        lifepoint: 50,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '11': {
        name: 'B. Skull Dragon',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 40,
        lifepoint: 40,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '12': {
        name: 'Baby Dragon',
        type: 'dragon',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Fly, No family pros or cons.',
        crests: 'SSSSMD2',
      },
      '13': {
        name: 'Barrel Dragon',
        type: 'dragon',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 40,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '14': {
        name: 'Basic Insect',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: '',
        crests: 'SSSSMD2',
      },
      '15': {
        name: 'Battle Ox',
        type: 'beast',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '16': {
        name: 'Battle Steer',
        type: 'beast',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '17': {
        name: 'Battle Warrior',
        type: 'warrior',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'Adds 1 attacks crest to own crest pool. (Dimension) Able to attack flying monsters.',
        crests: 'SSSSMD2',
      },
      '18': {
        name: 'Beautiful Headhuntress',
        type: 'warrior',
        level: 3,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '19': {
        name: 'Beaver Warrior',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '20': {
        name: 'Beta The Magnet Warrior',
        type: 'warrior',
        level: 2,
        attack: 10,
        defense: 20,
        lifepoint: 20,
        ability:
          'While one Alpha The Magnet Warrior is in the dungeon, this monster adds 10 extra Attack Power points to itself.',
        crests: 'SSSM2A2G',
      },
      '21': {
        name: 'Big Shield Gardna',
        type: 'warrior',
        level: 2,
        attack: 10,
        defense: 40,
        lifepoint: 20,
        ability:
          'Without spending a Defense Crest, this monster can defend. Whenever this effect is used, this monster loses 10 Defense Power points permanently.',
        crests: 'SSSM2A2G',
      },
      '22': {
        name: 'Black Luster Soldier',
        type: 'warrior',
        level: 4,
        attack: 40,
        defense: 30,
        lifepoint: 50,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '23': {
        name: 'Blackland Fire Dragon',
        type: 'dragon',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: '',
        crests: 'SSSM2A2G',
      },
      '24': {
        name: 'Blast Lizard',
        type: 'beast',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability: 'Destroys 1 foe Add 1 magic crest/level. [Gx3]',
        crests: 'SSSM2A2G',
      },
      '25': {
        name: 'Bubonic Vermin',
        type: 'beast',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability:
          'You can only use this effect once per turn. Perform your double dice roll one more time.',
        crests: 'SSSSMD2',
      },
      '26': {
        name: 'Buster Blader',
        type: 'warrior',
        level: 3,
        attack: 40,
        defense: 10,
        lifepoint: 30,
        ability:
          'This monster will not be affected by any attacks or effects produced by a monster from the Dragon tribe.',
        crests: 'SSMMAT2',
      },
      '27': {
        name: 'Cannon Soldier',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability:
          'Sacrifice 1 of your monsters in the dungeon, other that this one. Destroy one of your opponent\'s monsters in the dungeon. [Gx3]',
        crests: 'SSMMAT2',
      },
      '28': {
        name: 'Castle of D. Magic',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 20,
        lifepoint: 20,
        ability: 'Reduces damage by 20 when attacked. [Dx2]',
        crests: 'SSSM2A2G',
      },
      '29': {
        name: 'Catapult Turtle',
        type: 'beast',
        level: 2,
        attack: 10,
        defense: 30,
        lifepoint: 20,
        ability:
          'When this monster is Summoned, you can destroy one monster in the dungeon with the Flying ability. [Gx3]',
        crests: 'SSSM2A2G',
      },
      '30': {
        name: 'Celtic Guardian',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 10,
        ability:
          'This monster adds an additional 10 Attack Power points to itself for every Attack Crests spent (you can only use this effect once per turn). [Ax1] \nThis monster adds an additional 10 Defense Power points to itself for every Defense Crests spent (you can only use this effect once per turn). [Dx1]',
        crests: 'SSSM2A2G',
      },
      '31': {
        name: 'Chimera the Flying Mythical Beast',
        type: 'beast',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'This monster gains the Flying ability for one turn. [Tx2]',
        crests: 'SSSM2A2G',
      },
      '32': {
        name: 'Clown Zombie',
        type: 'zombie',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Tunneling, No family pros or cons.',
        crests: 'SSSSMD2',
      },
      '33': {
        name: 'Cocoon of Evolution',
        type: 'beast',
        level: 2,
        attack: 10,
        defense: 40,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '34': {
        name: 'Crass Clown',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: '',
        crests: 'SSSSMD2',
      },
      '35': {
        name: 'Crater Creator',
        type: 'item',
        level: 4,
        ability: 'Destroys all monsters in the dungeon.',
        crests: 'SM2ADG2T',
      },
      '36': {
        name: 'Crawling Dragon #1',
        type: 'dragon',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability:
          'Place a "Shelled Ground" counter anywhere on the Field EXCEPT in a square beside either you or your opponent\'s OldMonster Lord. Players cannot place Dungeon Pieces on any square where a Shelled Ground counter is located. [Gx4]',
        crests: 'SSSM2A2G',
      },
      '37': {
        name: 'Crocozaurus',
        type: 'beast',
        level: 4,
        attack: 30,
        defense: 20,
        lifepoint: 50,
        ability:
          'This monster adds 10 extra Attack power points to itself if you spend 1 extra Attack Crest when attacking. You can add a maximum of 30 additional Attack power points (by spending 3 extra Attack Crests) per one turn. [Ax?]',
        crests: 'SM2ADG2T',
      },
      '38': {
        name: 'Curse of Dragon',
        type: 'dragon',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'Fly',
        crests: 'SSMMAT2',
      },
      '39': {
        name: 'Dancing Elf',
        type: 'warrior',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '40': {
        name: 'Dark Assailant',
        type: 'zombie',
        level: 3,
        attack: 10,
        defense: 20,
        lifepoint: 20,
        ability:
          'This monster can move any item already in the dungeon a maximum of two squares. [Gx2]\nThis monster voids the effect of one item in the dungeon for one turn. [Tx3]',
        crests: 'SSMMAT2',
      },
      '41': {
        name: 'Dark Chimera',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Fly.\nDestroy one Magic Crest on your opponent\'s Crest Counter. [Gx2]',
        crests: 'SSSM2A2G',
      },
      '42': {
        name: 'Dark Magician',
        type: 'spellcaster',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 30,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '43': {
        name: 'Dark Magician Arkana',
        type: 'spellcaster',
        level: 3,
        attack: 30,
        defense: 20,
        lifepoint: 20,
        ability:
          'Without spending an Attack Crest, this monster can attack.\nFor one turn, your other monsters in the dungeon that have already performed an action in the turn (movement or a normal attack) can act again. [Gx6]',
        crests: 'SSMMAT2',
      },
      '44': {
        name: 'Dark Magician Girl',
        type: 'spellcaster',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'Add one Magic Crest to your Crest Counter',
        crests: 'SSMMAT2',
      },
      '45': {
        name: 'Dark Necrofear',
        type: 'spellcaster',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 20,
        ability:
          'You can only activate this effect when this monster is destroyed. Gain control permanently of one opponent\'s monster. [Tx3]',
        crests: 'SM2ADG2T',
      },
      '46': {
        name: 'Dark Ruler Ha Des',
        type: 'zombie',
        level: 3,
        attack: 20,
        defense: 30,
        lifepoint: 20,
        ability:
          'You can only use this effect once and during an opponent\'s turn. Place one 1 Damage Marker on each opponent\'s monster within 3 squares from this monster. [Tx3]',
        crests: 'SSMMAT2',
      },
      '47': {
        name: 'Dark Sage',
        type: 'spellcaster',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability:
          'When you summon this monster, the number of Magic Crests in your Crest Counter becomes 10.',
        crests: 'SM2ADG2T',
      },
      '48': {
        name: 'Dark-eyes Illusionist',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'When a monster is selected as the target of an attack or a special ability, you can negate that attack or ability. [Tx4]\nFor one turn, change the tribe of all monsters in the dungeon to the tribe of your choice. [Gx4]',
        crests: 'SSMMAT2',
      },
      '49': {
        name: 'Darkfire Dragon',
        type: 'dragon',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'When you summon this monster, add one Movement Crest to your Crest Counter.\n\nThis monster gains the Flying ability for one turn. [Gx1]',
        crests: 'SSSSMD2',
      },
      '50': {
        name: 'Declaration of Despair',
        type: 'item',
        level: 1,
        ability: 'Destroys 1 magic crest in own crest pool.',
        crests: 'SSSSMD2',
      },
      '51': {
        name: 'Dokurorider',
        type: 'zombie',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '52': {
        name: 'Dragon Piper',
        type: 'spellcaster',
        level: 1,
        defense: 10,
        lifepoint: 10,
        ability: 'Limits Dragon monsters 1 move/ 2 turns. (in play)',
        crests: 'SSSSMD2',
      },
      '53': {
        name: 'Dunames Dark Witch',
        type: 'spellcaster',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability:
          'Add permanently 10 extra Defense Power points to one of your monsters in the dungeon, other than this one. [Gx3]\nReduce permanently 10 Attack Power points to one opponent\'s monster in the dungeon. [Gx3]',
        crests: 'SSSM2A2G',
      },
      '54': {
        name: 'Energy Disk',
        type: 'item',
        level: 1,
        ability: 'Raises a monsters attack by 20.',
        crests: 'SSSSMD2',
      },
      '55': {
        name: 'Exodia of Forbidden',
        type: 'spellcaster',
        level: 4,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'Automatic win if the 4 limbs exist. (Dimension)',
        crests: 'SM2ADG2T',
      },
      '56': {
        name: 'Exploding Disk',
        type: 'item',
        level: 3,
        ability: 'Removes 2 hearts from a monster.',
        crests: 'SSMMAT2',
      },
      '57': {
        name: 'Faceless Mage',
        type: 'spellcaster',
        level: 3,
        attack: 20,
        defense: 30,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '58': {
        name: 'Feral Imp',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 20,
        lifepoint: 10,
        ability: 'Prevents all flying. (In play)',
        crests: 'SSSM2A2G',
      },
      '59': {
        name: 'Fiend\'s Mirror',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '60': {
        name: 'Flame Swordsman',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '61': {
        name: 'Flying Penguin',
        type: 'beast',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '62': {
        name: 'Gaia the Dragon Champion',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 30,
        lifepoint: 40,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '63': {
        name: 'Gaia The Fierce Knight',
        type: 'warrior',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 40,
        ability: 'Able to attack flying monsters.',
        crests: 'SM2ADG2T',
      },
      '64': {
        name: 'Gate Guardian',
        type: 'warrior',
        level: 4,
        attack: 40,
        defense: 40,
        lifepoint: 50,
        ability: 'Shifts damage to an ally.',
        crests: 'SM2ADG2T',
      },
      '65': {
        name: 'Gator Dragon',
        type: 'dragon',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 30,
        ability: 'Reduces attack damage by defense crest X 10. [Dx?]',
        crests: 'SSSM2A2G',
      },
      '66': {
        name: 'Gemini Elf',
        type: 'spellcaster',
        level: 3,
        attack: 40,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '67': {
        name: 'Giant Flea',
        type: 'beast',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '68': {
        name: 'Giant rock soldier',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 30,
        lifepoint: 20,
        ability: 'Removes one obstacle. [Gx2]',
        crests: 'SSSM2A2G',
      },
      '69': {
        name: 'Gluminizer',
        type: 'item',
        level: 2,
        ability: 'Doubles movement cost for all. (Dimension)',
        crests: 'SSSM2A2G',
      },
      '70': {
        name: 'Great Moth',
        type: 'beast',
        level: 3,
        attack: 30,
        defense: 30,
        lifepoint: 40,
        ability: 'Fly',
        crests: 'SSMMAT2',
      },
      '71': {
        name: 'Hane-Hane',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '72': {
        name: 'Harpie Lady',
        type: 'beast',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability: 'Fly, Destroys one tunneling monster. (Dimension) [Gx3]',
        crests: 'SSSM2A2G',
      },
      '73': {
        name: 'Harpie Lady Sisters',
        type: 'beast',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'Destroys all tunnellers. (Dimension) [Gx4]',
        crests: 'SSMMAT2',
      },
      '74': {
        name: 'Hitotsu-me Giant',
        type: 'beast',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '75': {
        name: 'Jellyfish',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Raises defense of all Beast monsters by 10 (In Play)',
        crests: 'SSSSMD2',
      },
      '76': {
        name: 'Jinzo',
        type: 'warrior',
        level: 3,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '77': {
        name: 'Jirai Gumo',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability: 'Tunneling',
        crests: 'SSSSMD2',
      },
      '78': {
        name: 'Kanan the Swordmistress',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '79': {
        name: 'Karbonala Warrior',
        type: 'warrior',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Raises attack of all warriors by 10. (in play)',
        crests: 'SSSSMD2',
      },
      '80': {
        name: 'Kazejin',
        type: 'spellcaster',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability: 'Shifts damage to an ally [Tx3]',
        crests: 'SM2ADG2T',
      },
      '81': {
        name: 'Killer Needle',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Able to attack flying monsters',
        crests: 'SSSSMD2',
      },
      '82': {
        name: 'Knight of Twin Swords',
        type: 'warrior',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 30,
        ability:
          'Moves 2 squares for 1 movement crests. attacks 1 foe up to 3 times/turn. (on attack) [Ax?]',
        crests: 'SSSM2A2G',
      },
      '83': {
        name: 'Koumori Dragon',
        type: 'dragon',
        level: 2,
        attack: 10,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '84': {
        name: 'Kuriboh',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '85': {
        name: 'L Arm of Forbidden',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '86': {
        name: 'L Leg of Forbidden',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '87': {
        name: 'Larvae Moth',
        type: 'beast',
        level: 1,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '88': {
        name: 'Lord of D.',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Protects all dragon monsters. (In Play)',
        crests: 'SSSM2A2G',
      },
      '89': {
        name: 'Magician Dragon',
        type: 'dragon',
        level: 3,
        attack: 20,
        defense: 10,
        lifepoint: 40,
        ability:
          'Adds enemy defense to own defense. [Tx3] Destroys all within 3 x 3 grid. [Gx3]',
        crests: 'SSMMAT2',
      },
      '90': {
        name: 'Magician of Black Chaos',
        type: 'spellcaster',
        level: 4,
        attack: 40,
        defense: 30,
        lifepoint: 40,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '91': {
        name: 'Mammoth Graveyard',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Tunneling, Raises attack of all Beats monsters by 10. (in play)',
        crests: 'SSSSMD2',
      },
      '92': {
        name: 'Man-eater Bug',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '93': {
        name: 'Medical Aid Kit',
        type: 'item',
        level: 2,
        ability: 'Restores 2 hearts to a monster.',
        crests: 'SSSM2A2G',
      },
      '94': {
        name: 'Metal Guardian',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 30,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '95': {
        name: 'Metal Zoa',
        type: 'spellcaster',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '96': {
        name: 'Meteor B. Dragon',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 30,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '97': {
        name: 'Meteor Dragon',
        type: 'dragon',
        level: 3,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability: 'Fly',
        crests: 'SSMMAT2',
      },
      '98': {
        name: 'Mighty Mage',
        type: 'spellcaster',
        level: 4,
        attack: 30,
        defense: 20,
        lifepoint: 50,
        ability: 'attacks an enemy 2 squares away. [Gx1]',
        crests: 'SM2ADG2T',
      },
      '99': {
        name: 'Millennium Shield',
        type: 'warrior',
        level: 3,
        defense: 40,
        lifepoint: 10,
        ability: 'This item cant move.',
        crests: 'SSMMAT2',
      },
      '100': {
        name: 'Mushroom Man',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '101': {
        name: 'Mystic Horseman',
        type: 'beast',
        level: 2,
        attack: 20,
        defense: 10,
        lifepoint: 40,
        ability: 'Adds damage to attack once per turn. [Gx1]',
        crests: 'SSSM2A2G',
      },
      '102': {
        name: 'Mystic Lamp',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Raises defense of all spellcaster monsters by 10. (In play)',
        crests: 'SSSSMD2',
      },
      '103': {
        name: 'Mystical Elf',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 20,
        lifepoint: 20,
        ability: 'Restores 1 heart to all allies. (dimension)',
        crests: 'SSSSMD2',
      },
      '104': {
        name: 'Orgoth the Relentless',
        type: 'warrior',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 30,
        ability: 'Raises attack by 10.',
        crests: 'SSMMAT2',
      },
      '105': {
        name: 'Parrot Dragon',
        type: 'dragon',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Fly, Raises defense of all dragon monsters by 10. (In play)',
        crests: 'SSSSMD2',
      },
      '106': {
        name: 'Pendulum Machine',
        type: 'spellcaster',
        level: 3,
        attack: 20,
        defense: 30,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '107': {
        name: 'Penguin Soldier',
        type: 'beast',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '108': {
        name: 'Perfectly Ultimate',
        type: 'beast',
        level: 4,
        attack: 40,
        defense: 40,
        lifepoint: 50,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '109': {
        name: 'Petit Dragon',
        type: 'dragon',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Raises attack of dragon monsters by 10. (In Play)',
        crests: 'SSSSMD2',
      },
      '110': {
        name: 'Pumpking the King of Ghosts',
        type: 'zombie',
        level: 3,
        attack: 20,
        defense: 30,
        lifepoint: 30,
        ability: 'Reduces damage by 30 when attacked. [Dx3]',
        crests: 'SSMMAT2',
      },
      '111': {
        name: 'R Arm of Forbidden',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '112': {
        name: 'R Leg of Forbidden',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '113': {
        name: 'R. eye B. M. Dragon',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 40,
        lifepoint: 30,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '114': {
        name: 'Rabid Horseman',
        type: 'beast',
        level: 3,
        attack: 30,
        defense: 20,
        lifepoint: 40,
        ability:
          'attack crest raises attack by 10 up to twice/turn. (In attack) [Ax?]',
        crests: 'SSMMAT2',
      },
      '115': {
        name: 'Red Archery Girl',
        type: 'warrior',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '116': {
        name: 'Red-eyes B. Dragon',
        type: 'dragon',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 30,
        ability: 'Fly',
        crests: 'SM2ADG2T',
      },
      '117': {
        name: 'Relinquished',
        type: 'spellcaster',
        level: 1,
        lifepoint: 10,
        ability: 'Sacrifices self to steal 1 enemy. [Gx10]',
        crests: 'SSSSMD2',
      },
      '118': {
        name: 'Resurrection Scroll',
        type: 'item',
        level: 2,
        ability: 'Resurrects 1 destroyed ally.',
        crests: 'SSSM2A2G',
      },
      '119': {
        name: 'Rock Ogre Grotto',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Raises defense of all spellcaster monsters by 10 (in play)',
        crests: 'SSSSMD2',
      },
      '120': {
        name: 'Rogue Doll',
        type: 'spellcaster',
        level: 3,
        attack: 30,
        defense: 20,
        lifepoint: 20,
        ability:
          'Restores 1 heart to 2 allied monsters. (Dimension) [Gx3]',
        crests: 'SSMMAT2',
      },
      '121': {
        name: 'Ryu-Kishin',
        type: 'spellcaster',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '122': {
        name: 'Ryu-kishin Powered',
        type: 'spellcaster',
        level: 2,
        attack: 30,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '123': {
        name: 'Saggi the Dark Clown',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Reduces damage to one ally by 10. [Dx2]',
        crests: 'SSSSMD2',
      },
      '124': {
        name: 'Sanga of the Thunder',
        type: 'spellcaster',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability: 'Shifts damage to an ally [Tx3]',
        crests: 'SM2ADG2T',
      },
      '125': {
        name: 'Sangan',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '126': {
        name: 'Shadow Specter',
        type: 'zombie',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '127': {
        name: 'Skelengel',
        type: 'warrior',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Raises defense of all warrior monsters by 10 (In Play)',
        crests: 'SSSSMD2',
      },
      '128': {
        name: 'Slot machine',
        type: 'spellcaster',
        level: 3,
        attack: 20,
        defense: 20,
        lifepoint: 30,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '129': {
        name: 'Strike Ninja',
        type: 'warrior',
        level: 3,
        attack: 20,
        defense: 10,
        lifepoint: 20,
        ability:
          'Moves 3 squares for 1 movement crest. Protects self from attacks and effects. [Tx2]',
        crests: 'SSMMAT2',
      },
      '130': {
        name: 'Stuffed Animal',
        type: 'warrior',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '131': {
        name: 'Suijin',
        type: 'beast',
        level: 4,
        attack: 30,
        defense: 30,
        lifepoint: 30,
        ability: 'Shifts damage to an ally [Tx3]',
        crests: 'SM2ADG2T',
      },
      '132': {
        name: 'Summoned Skull',
        type: 'spellcaster',
        level: 4,
        attack: 40,
        defense: 20,
        lifepoint: 40,
        ability: 'N/A',
        crests: 'SM2ADG2T',
      },
      '133': {
        name: 'Swamp Battleguard',
        type: 'warrior',
        level: 2,
        attack: 20,
        defense: 20,
        lifepoint: 20,
        ability:
          'attack crests raises attack by 10 once a turn. (on attack) [Ax1]',
        crests: 'SSSM2A2G',
      },
      '134': {
        name: 'The 13th Grave',
        type: 'zombie',
        level: 2,
        defense: 10,
        lifepoint: 10,
        ability: 'Tunneling, Removes 1 heart from enemy and self. [Gx2]',
        crests: 'SSSM2A2G',
      },
      '135': {
        name: 'The Snake Hair',
        type: 'zombie',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability:
          'Fly, Raises defense of all zombie monsters by 10. (in play)',
        crests: 'SSSSMD2',
      },
      '136': {
        name: 'Thousand Dragon',
        type: 'dragon',
        level: 2,
        attack: 30,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSSM2A2G',
      },
      '137': {
        name: 'Thousand-eyes Restrict',
        type: 'spellcaster',
        level: 4,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Gain control of 1 foe/turn. [Gx8]',
        crests: 'SM2ADG2T',
      },
      '138': {
        name: 'Three-legged zombies',
        type: 'zombie',
        level: 1,
        attack: 20,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '139': {
        name: 'Thunder Ball',
        type: 'spellcaster',
        level: 3,
        attack: 10,
        defense: 10,
        lifepoint: 30,
        ability:
          'Rolls to destroy one foe. Add 1 defense crest per level. [Gx3]',
        crests: 'SSMMAT2',
      },
      '140': {
        name: 'Time Machine',
        type: 'item',
        level: 1,
        ability: 'Returns monster to its last lactation.',
        crests: 'SSSSMD2',
      },
      '141': {
        name: 'Time Wizard',
        type: 'spellcaster',
        level: 1,
        defense: 10,
        lifepoint: 10,
        ability: 'Destroys monster with least attack. (dimension)',
        crests: 'SSSSMD2',
      },
      '142': {
        name: 'Trap Bandit',
        type: 'item',
        level: 1,
        ability: 'Destroys 1 trap crest in own crest pool.',
        crests: 'SSSSMD2',
      },
      '143': {
        name: 'Twin-Headed Dragon',
        type: 'dragon',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability:
          'Tunneling, Adds 1 trap crest to own crest pool. (Dimension)',
        crests: 'SSSSMD2',
      },
      '144': {
        name: 'Twin-headed Thunder Dragon',
        type: 'dragon',
        level: 3,
        attack: 40,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '145': {
        name: 'Warp Vortex',
        type: 'item',
        level: 3,
        ability: 'Moves OldMonster to another Vortex. (Dimension)',
        crests: 'SSMMAT2',
      },
      '146': {
        name: 'Winged Dragon',
        type: 'dragon',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Fly, Prevents all tunneling. (In play)',
        crests: 'SSSM2A2G',
      },
      '147': {
        name: 'Witch\'s Apprentice',
        type: 'spellcaster',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'N/A',
        crests: 'SSSSMD2',
      },
      '148': {
        name: 'Yaranzo',
        type: 'zombie',
        level: 2,
        attack: 10,
        defense: 10,
        lifepoint: 20,
        ability: 'Trades 3 crests in own pool for 1. (Dimension)',
        crests: 'SSSM2A2G',
      },
      '149': {
        name: 'Zoa',
        type: 'spellcaster',
        level: 3,
        attack: 30,
        defense: 20,
        lifepoint: 20,
        ability: 'N/A',
        crests: 'SSMMAT2',
      },
      '150': {
        name: 'Zombie Warrior',
        type: 'zombie',
        level: 1,
        attack: 10,
        defense: 10,
        lifepoint: 10,
        ability: 'Raises attack of all Zombie monsters by 10. (in play)',
        crests: 'SSSSMD2',
      },
    },
  },
  player: {
    default: {
      radius: 20,
      pool: [2, 41, 42, 21, 7, 24, 32, 6, 30, 68, 104, 109, 111, 123, 26],
    },
    team: {
      colors: {
        A: new Color(255, 0, 0),
        B: new Color(0, 255, 0),
        C: new Color(0, 0, 255),
        D: new Color(210, 210, 210),
      },
      positions: {
        A: 'g1',
        B: 'g19',
        C: 'a10',
        D: 'm10',
      },
    },
  },
});
